language: c
script: asdf plugin-test goreleaser https://github.com/endorama/asdf-goreleaser.git 'goreleaser --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
